# Generated by Django 2.1.5 on 2019-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databases',
            name='host',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='name',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='password',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='port',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='user',
        ),
        migrations.AddField(
            model_name='databases',
            name='ENGINE',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='HOST',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='NAME',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='PASSWORD',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='PORT',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='USER',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
