# Generated by Django 2.1.5 on 2019-05-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_template', '0002_auto_20190501_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
